package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EduAcademic generated by hbm2java
 */
@Entity
@Table(name="edu_academic")
public class EduAcademic  extends BaseEntity {

    // Fields

     private String fromMonth;
     private Integer fromYear;
     private String toMonth;
     private Integer toYear;
     private Set<EduStudent> eduStudents = new HashSet<EduStudent>(0);

     // Constructors

    /** default constructor */
    public EduAcademic() {
    }

    // Property accessors

    @Column(name="From_Month", unique=false, nullable=true, insertable=true, updatable=true, length=15)
    public String getFromMonth() {
        return this.fromMonth;
    }

    public void setFromMonth(String fromMonth) {
        this.fromMonth = fromMonth;
    }

    @Column(name="From_Year", unique=false, nullable=true, insertable=true, updatable=true)
    public Integer getFromYear() {
        return this.fromYear;
    }

    public void setFromYear(Integer fromYear) {
        this.fromYear = fromYear;
    }

    @Column(name="To_Month", unique=false, nullable=true, insertable=true, updatable=true, length=15)
    public String getToMonth() {
        return this.toMonth;
    }

    public void setToMonth(String toMonth) {
        this.toMonth = toMonth;
    }

    @Column(name="To_Year", unique=false, nullable=true, insertable=true, updatable=true)
    public Integer getToYear() {
        return this.toYear;
    }

    public void setToYear(Integer toYear) {
        this.toYear = toYear;
    }

    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduAcademic")
    public Set<EduStudent> getEduStudents() {
        return this.eduStudents;
    }

    public void setEduStudents(Set<EduStudent> eduStudents) {
        this.eduStudents = eduStudents;
    }
}
