package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EduClass generated by hbm2java
 */
@Entity
@Table(name="edu_class")
public class EduClass  extends BaseEntity {

    // Fields

     private String className;
     private Set<EduInstitutionClass> eduInstitutionClasses = new HashSet<EduInstitutionClass>(0);
     private Set<EduDocument> eduDocuments = new HashSet<EduDocument>(0);

     // Constructors

    /** default constructor */
    public EduClass() {
    }

    // Property accessors

    @Column(name="Class_Name", unique=false, nullable=true, insertable=true, updatable=true, length=64)
    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduClass")
    public Set<EduInstitutionClass> getEduInstitutionClasses() {
        return this.eduInstitutionClasses;
    }

    public void setEduInstitutionClasses(Set<EduInstitutionClass> eduInstitutionClasses) {
        this.eduInstitutionClasses = eduInstitutionClasses;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduClass")
    public Set<EduDocument> getEduDocuments() {
        return this.eduDocuments;
    }

    public void setEduDocuments(Set<EduDocument> eduDocuments) {
        this.eduDocuments = eduDocuments;
    }
}
