package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EduCourse generated by hbm2java
 */
@Entity
@Table(name="edu_course")
public class EduCourse  extends BaseEntity {

    // Fields
     private String courseName;
     private Set<EduDocument> eduDocuments = new HashSet<EduDocument>(0);
     private Set<EduCourseBranch> eduCourseBranchs = new HashSet<EduCourseBranch>(0);

     // Constructors

    /** default constructor */
    public EduCourse() {
    }

    // Property accessors

    @Column(name="Course_Name", unique=false, nullable=true, insertable=true, updatable=true, length=124)
    public String getCourseName() {
        return this.courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

   @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduCourse")
    public Set<EduDocument> getEduDocuments() {
        return this.eduDocuments;
    }

    public void setEduDocuments(Set<EduDocument> eduDocuments) {
        this.eduDocuments = eduDocuments;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduCourse")
    public Set<EduCourseBranch> getEduCourseBranchs() {
        return this.eduCourseBranchs;
    }

    public void setEduCourseBranchs(Set<EduCourseBranch> eduCourseBranchs) {
        this.eduCourseBranchs = eduCourseBranchs;
    }

    public String toString()
    {
    	StringBuffer bufRet = new StringBuffer();
    	bufRet.append(super.toString());
    	bufRet.append("courseName:  " + courseName + "\r\n");
    	return bufRet.toString();
    }



}
