package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EduCourseBranch generated by hbm2java
 */
@Entity
@Table(name="edu_course_branch")
public class EduCourseBranch  extends BaseEntity {

    // Fields
     private EduCourse eduCourse;
     private String branchName;
     private Set<EduDocument> eduDocuments = new HashSet<EduDocument>(0);
     private Set<EduInstitutionBranch> eduInstitutionBranchs = new HashSet<EduInstitutionBranch>(0);

     // Constructors

    /** default constructor */
    public EduCourseBranch() {
    }

    // Property accessors

@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Course_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduCourse getEduCourse() {
        return this.eduCourse;
    }

    public void setEduCourse(EduCourse eduCourse) {
        this.eduCourse = eduCourse;
    }

    @Column(name="Branch_Name", unique=false, nullable=true, insertable=true, updatable=true)
    public String getBranchName() {
        return this.branchName;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduCourseBranch")
    public Set<EduDocument> getEduDocuments() {
        return this.eduDocuments;
    }

    public void setEduDocuments(Set<EduDocument> eduDocuments) {
        this.eduDocuments = eduDocuments;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduCourseBranch")
    public Set<EduInstitutionBranch> getEduInstitutionBranchs() {
        return this.eduInstitutionBranchs;
    }

    public void setEduInstitutionBranchs(Set<EduInstitutionBranch> eduInstitutionBranchs) {
        this.eduInstitutionBranchs = eduInstitutionBranchs;
    }
}
