package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EduExam generated by hbm2java
 */
@Entity
@Table(name="edu_exam")
public class EduExam  extends BaseEntity {

    // Fields

     private String examName;
     private int maxMarks;
     private Set<EduStudentExam> eduStudentExams = new HashSet<EduStudentExam>(0);

     // Constructors

    /** default constructor */
    public EduExam() {
    }

    // Property accessors
    @Column(name="Exam_Name", unique=false, nullable=true, insertable=true, updatable=true, length=64)
    public String getExamName() {
        return this.examName;
    }

    public void setExamName(String examName) {
        this.examName = examName;
    }

    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduExam")
    public Set<EduStudentExam> getEduStudentExams() {
        return this.eduStudentExams;
    }

    public void setEduStudentExams(Set<EduStudentExam> eduStudentExams) {
        this.eduStudentExams = eduStudentExams;
    }

	/**
	 * @return the maxMarks
	 */
    @Column(name="max_marks")
	public int getMaxMarks() {
		return maxMarks;
	}

	/**
	 * @param maxMarks the maxMarks to set
	 */
	public void setMaxMarks(int maxMarks) {
		this.maxMarks = maxMarks;
	}
}
