package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EduInstitutionClass generated by hbm2java
 */
@Entity
@Table(name="edu_institution_class")
public class EduInstitutionClass  extends BaseEntity {

    // Fields
     private EduInstitution eduInstitution;
     private EduClass eduClass;
     private Set<EduInstClassSubject> eduInstClassSubjects = new HashSet<EduInstClassSubject>(0);
     private Set<EduInstClassSection> eduInstClassSections = new HashSet<EduInstClassSection>(0);

     // Constructors

    /** default constructor */
    public EduInstitutionClass() {
    }

    // Property accessors

@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Institution_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduInstitution getEduInstitution() {
        return this.eduInstitution;
    }

    public void setEduInstitution(EduInstitution eduInstitution) {
        this.eduInstitution = eduInstitution;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Class_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduClass getEduClass() {
        return this.eduClass;
    }

    public void setEduClass(EduClass eduClass) {
        this.eduClass = eduClass;
    }

    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduInstitutionClass")
    public Set<EduInstClassSubject> getEduInstClassSubjects() {
        return this.eduInstClassSubjects;
    }

    public void setEduInstClassSubjects(Set<EduInstClassSubject> eduInstClassSubjects) {
        this.eduInstClassSubjects = eduInstClassSubjects;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduInstitutionClass")
    public Set<EduInstClassSection> getEduInstClassSections() {
        return this.eduInstClassSections;
    }

    public void setEduInstClassSections(Set<EduInstClassSection> eduInstClassSections) {
        this.eduInstClassSections = eduInstClassSections;
    }
}
