package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EduInstBranchSection generated by hbm2java
 */
@Entity
@Table(name="edu_inst_branch_section")
public class EduInstBranchSection  extends BaseEntity {

    // Fields

     private EduSection eduSection;
     private EduInstitutionBranch eduInstitutionBranch;
     private Set<EduStudent> eduStudents = new HashSet<EduStudent>(0);

     // Constructors

    /** default constructor */
    public EduInstBranchSection() {
    }

    // Property accessors
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Section_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduSection getEduSection() {
        return this.eduSection;
    }

    public void setEduSection(EduSection eduSection) {
        this.eduSection = eduSection;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Institution_Branch_Id", unique=false, nullable=true, insertable=true, updatable=true)
    public EduInstitutionBranch getEduInstitutionBranch() {
        return this.eduInstitutionBranch;
    }

    public void setEduInstitutionBranch(EduInstitutionBranch eduInstitutionBranch) {
        this.eduInstitutionBranch = eduInstitutionBranch;
    }

    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduInstBranchSection")
    public Set<EduStudent> getEduStudents() {
        return this.eduStudents;
    }

    public void setEduStudents(Set<EduStudent> eduStudents) {
        this.eduStudents = eduStudents;
    }
}
