package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * EduReference generated by hbm2java
 */
@Entity
@Table(name="edu_reference")
public class EduReference  implements Serializable {

    // Fields
	 private int pkId;
     private int refId;
     private String refName;
     private String refListName;
     private String langId;

     // Constructors

    /** default constructor */
    public EduReference() {
    }

    // Property accessors

    @Column(name="ref_id", unique=false, nullable=false, insertable=true, updatable=true)
    public int getRefId() {
        return this.refId;
    }

    public void setRefId(int refId) {
        this.refId = refId;
    }

    @Column(name="ref_name", unique=false, nullable=false, insertable=true, updatable=true)
    public String getRefName() {
        return this.refName;
    }

    public void setRefName(String refName) {
        this.refName = refName;
    }

    @Column(name="ref_list_name", unique=false, nullable=false, insertable=true, updatable=true)
    public String getRefListName() {
        return this.refListName;
    }

    public void setRefListName(String refListName) {
        this.refListName = refListName;
    }

    @Column(name="lang_id", unique=false, nullable=true, insertable=true, updatable=true, length=20)
    public String getLangId() {
        return this.langId;
    }

    public void setLangId(String langId) {
        this.langId = langId;
    }

 // Property accessors
    @Id
	@Column(name="Pk_Id", unique=true, nullable=false, insertable=true, updatable=true)
    public int getPkId() {
        return this.pkId;
    }

    public void setPkId(int pkId) {
        this.pkId = pkId;
    }

}
