package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EduStudentMessage generated by hbm2java
 */
@Entity
@Table(name="edu_student_message")
public class EduStudentMessage  extends BaseEntity {

    // Fields
     private EduUser eduUser;
     private EduStudent eduStudent;
     private String message;
     private char isSms;
     private char isEmail;
     private Character messageType;
     private Date sentDate;
     private Character smsStatus;
     private Character emailStatus;

     // Constructors

    /** default constructor */
    public EduStudentMessage() {
    }

    // Property accessors

@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_User_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduUser getEduUser() {
        return this.eduUser;
    }

    public void setEduUser(EduUser eduUser) {
        this.eduUser = eduUser;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Student_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduStudent getEduStudent() {
        return this.eduStudent;
    }

    public void setEduStudent(EduStudent eduStudent) {
        this.eduStudent = eduStudent;
    }

    @Column(name="Message", unique=false, nullable=false, insertable=true, updatable=true)
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Column(name="Is_SMS", unique=false, nullable=false, insertable=true, updatable=true, length=1)
    public char getIsSms() {
        return this.isSms;
    }

    public void setIsSms(char isSms) {
        this.isSms = isSms;
    }

    @Column(name="Is_Email", unique=false, nullable=false, insertable=true, updatable=true, length=1)
    public char getIsEmail() {
        return this.isEmail;
    }

    public void setIsEmail(char isEmail) {
        this.isEmail = isEmail;
    }

    @Column(name="Message_Type", unique=false, nullable=true, insertable=true, updatable=true, length=1)
    public Character getMessageType() {
        return this.messageType;
    }

    public void setMessageType(Character messageType) {
        this.messageType = messageType;
    }

    @Column(name="Sent_Date", unique=false, nullable=false, insertable=true, updatable=true, length=19)
    public Date getSentDate() {
        return this.sentDate;
    }

    public void setSentDate(Date sentDate) {
        this.sentDate = sentDate;
    }

    @Column(name="SMS_Status", unique=false, nullable=true, insertable=true, updatable=true, length=1)
    public Character getSmsStatus() {
        return this.smsStatus;
    }

    public void setSmsStatus(Character smsStatus) {
        this.smsStatus = smsStatus;
    }

    @Column(name="Email_Status", unique=false, nullable=true, insertable=true, updatable=true, length=1)
    public Character getEmailStatus() {
        return this.emailStatus;
    }

    public void setEmailStatus(Character emailStatus) {
        this.emailStatus = emailStatus;
    }
}
