package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EduStudent generated by hbm2java
 */
@Entity
@Table(name="edu_student")
public class EduStudent  extends BaseEntity {

    // Fields
     private EduAcademic eduAcademic;
     private EduInstBranchSection eduInstBranchSection;
     private EduInstClassSection eduInstClassSection;
     private String firstName;
     private String middleName;
     private String lastName;
     private String admissionNumber;
     private Date dateOfBirth;
     //private String stringDateOfBirth;
     private Set<EduStudentMessage> eduStudentMessages = new HashSet<EduStudentMessage>(0);
     private Set<EduStudentExam> eduStudentExams = new HashSet<EduStudentExam>(0);
     private Set<EduUserStudent> eduUserStudents = new HashSet<EduUserStudent>(0);

     // Constructors

    /** default constructor */
    public EduStudent() {
    }

    // Property accessors
 @ManyToOne(cascade={},
        fetch=FetchType.EAGER)

    @JoinColumn(name="Fk_Academic_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduAcademic getEduAcademic() {
        return this.eduAcademic;
    }

    public void setEduAcademic(EduAcademic eduAcademic) {
        this.eduAcademic = eduAcademic;
    }
@ManyToOne(cascade={},
        fetch=FetchType.EAGER)

    @JoinColumn(name="Fk_Inst_Branch_Section_Id", unique=false, nullable=true, insertable=true, updatable=true)
    public EduInstBranchSection getEduInstBranchSection() {
        return this.eduInstBranchSection;
    }

    public void setEduInstBranchSection(EduInstBranchSection eduInstBranchSection) {
        this.eduInstBranchSection = eduInstBranchSection;
    }
@ManyToOne(cascade={},
        fetch=FetchType.EAGER)

    @JoinColumn(name="Fk_Inst_Class_Section_Id", unique=false, nullable=true, insertable=true, updatable=true)
    public EduInstClassSection getEduInstClassSection() {
        return this.eduInstClassSection;
    }

    public void setEduInstClassSection(EduInstClassSection eduInstClassSection) {
        this.eduInstClassSection = eduInstClassSection;
    }

    @Column(name="First_Name", unique=false, nullable=false, insertable=true, updatable=true)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name="Middle_Name", unique=false, nullable=false, insertable=true, updatable=true)
    public String getMiddleName() {
        return this.middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    @Column(name="Last_Name", unique=false, nullable=false, insertable=true, updatable=true)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name="Admission_Number", unique=false, nullable=false, insertable=true, updatable=true, length=20)
    public String getAdmissionNumber() {
        return this.admissionNumber;
    }

    public void setAdmissionNumber(String admissionNumber) {
        this.admissionNumber = admissionNumber;
    }

    @Column(name="Date_Of_Birth", unique=false, nullable=false, insertable=true, updatable=true, length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.EAGER, mappedBy="eduStudent")
    public Set<EduStudentMessage> getEduStudentMessages() {
        return this.eduStudentMessages;
    }

    public void setEduStudentMessages(Set<EduStudentMessage> eduStudentMessages) {
        this.eduStudentMessages = eduStudentMessages;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.EAGER, mappedBy="eduStudent")
    public Set<EduStudentExam> getEduStudentExams() {
        return this.eduStudentExams;
    }

    public void setEduStudentExams(Set<EduStudentExam> eduStudentExams) {
        this.eduStudentExams = eduStudentExams;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.EAGER, mappedBy="eduStudent")
    public Set<EduUserStudent> getEduUserStudents() {
        return this.eduUserStudents;
    }

    public void setEduUserStudents(Set<EduUserStudent> eduUserStudents) {
        this.eduUserStudents = eduUserStudents;
    }

	/*public String getStringDateOfBirth() {
		return stringDateOfBirth;
	}

	public void setStringDateOfBirth(String stringDateOfBirth) {
		this.stringDateOfBirth = stringDateOfBirth;
	}*/
	
	public String toString()
    {
    	StringBuffer bufRet = new StringBuffer();
    	bufRet.append(super.toString());
    	bufRet.append("firstName:  " + firstName + "\r\n");
    	bufRet.append("middleName:  " + middleName + "\r\n");
    	bufRet.append("lastName:  " + lastName + "\r\n");
    	bufRet.append("admissionNumber:  " + admissionNumber + "\r\n");
    	//bufRet.append("stringDateOfBirth:  " + stringDateOfBirth + "\r\n");
    	bufRet.append("dateOfBirth:  " + dateOfBirth + "\r\n");
    	
    	return bufRet.toString();
    }
}
