package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EduStudentExam generated by hbm2java
 */
@Entity
@Table(name="edu_student_exam")
public class EduStudentExam  extends BaseEntity {

    // Fields

     private EduStudent eduStudent;
     private EduExam eduExam;
     private Set<EduStudentMarks> eduStudentMarkses = new HashSet<EduStudentMarks>(0);

     // Constructors

    /** default constructor */
    public EduStudentExam() {
    }

    // Property accessors

@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Student_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduStudent getEduStudent() {
        return this.eduStudent;
    }

    public void setEduStudent(EduStudent eduStudent) {
        this.eduStudent = eduStudent;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Exam_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduExam getEduExam() {
        return this.eduExam;
    }

    public void setEduExam(EduExam eduExam) {
        this.eduExam = eduExam;
    }

    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduStudentExam")
    public Set<EduStudentMarks> getEduStudentMarkses() {
        return this.eduStudentMarkses;
    }

    public void setEduStudentMarkses(Set<EduStudentMarks> eduStudentMarkses) {
        this.eduStudentMarkses = eduStudentMarkses;
    }
}
