package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import java.lang.StringBuffer;

/**
 * EduSubject generated by hbm2java
 */
@Entity
@Table(name="edu_subject")
public class EduSubject  extends BaseEntity {

    // Fields    
     private String subjectName;
     private String shortName;
     private int periods;
     private int periodsForTechEdu;
     private char hard;
     private Set<EduStudentMarks> eduStudentMarkses = new HashSet<EduStudentMarks>(0);
     private Set<EduInstBranchSubject> eduInstBranchSubjects = new HashSet<EduInstBranchSubject>(0);
     private Set<EduInstClassSubject> eduInstClassSubjects = new HashSet<EduInstClassSubject>(0);

     // Constructors

    /** default constructor */
    public EduSubject() {
    }

    // Property accessors
    
    @Column(name="Subject_Name", unique=false, nullable=true, insertable=true, updatable=true, length=124)
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    
    @Column(name="Short_Name", unique=false, nullable=true, insertable=true, updatable=true, length=30)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduSubject")
    public Set<EduStudentMarks> getEduStudentMarkses() {
        return this.eduStudentMarkses;
    }
    
    public void setEduStudentMarkses(Set<EduStudentMarks> eduStudentMarkses) {
        this.eduStudentMarkses = eduStudentMarkses;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduSubject")
    public Set<EduInstBranchSubject> getEduInstBranchSubjects() {
        return this.eduInstBranchSubjects;
    }
    
    public void setEduInstBranchSubjects(Set<EduInstBranchSubject> eduInstBranchSubjects) {
        this.eduInstBranchSubjects = eduInstBranchSubjects;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduSubject")
    public Set<EduInstClassSubject> getEduInstClassSubjects() {
        return this.eduInstClassSubjects;
    }
    
    public void setEduInstClassSubjects(Set<EduInstClassSubject> eduInstClassSubjects) {
        this.eduInstClassSubjects = eduInstClassSubjects;
    }
    
    public String toString()
    {
    	StringBuffer bufRet = new StringBuffer();
    	bufRet.append(super.toString());
    	bufRet.append("subjectName:  " + subjectName + "\r\n");
    	bufRet.append("shortName:  " + shortName + "\r\n");
    	return bufRet.toString();
    }

	/**
	 * @return the periods
	 */
    @Column(name="periods", unique=false, nullable=true, insertable=true, updatable=true)
	public int getPeriods() {
		return periods;
	}

	/**
	 * @param periods the periods to set
	 */
	public void setPeriods(int periods) {
		this.periods = periods;
	}

	/**
	 * @return the periodsForTechEdu
	 */
	 @Column(name="periods_for_tech_edu", unique=false, nullable=true, insertable=true, updatable=true)
	public int getPeriodsForTechEdu() {
		return periodsForTechEdu;
	}

	/**
	 * @param periodsForTechEdu the periodsForTechEdu to set
	 */
	public void setPeriodsForTechEdu(int periodsForTechEdu) {
		this.periodsForTechEdu = periodsForTechEdu;
	}

	/**
	 * @return the hard
	 */
    @Column(name="is_hard", unique=false, nullable=true, insertable=true, updatable=true)
	public char isHard() {
		return hard;
	}

	/**
	 * @param hard the hard to set
	 */
	public void setHard(char hard) {
		this.hard = hard;
	}

}
