package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EduSection generated by hbm2java
 */
@Entity
@Table(name="edu_section")
public class EduSection  extends BaseEntity {

    // Fields
     private String sectionName;
     private Set<EduInstBranchSection> eduInstBranchSections = new HashSet<EduInstBranchSection>(0);
     private Set<EduInstClassSection> eduInstClassSections = new HashSet<EduInstClassSection>(0);
     private Set<EduDocument> eduDocuments = new HashSet<EduDocument>(0);

     // Constructors

    /** default constructor */
    public EduSection() {
    }

    // Property accessors
    @Column(name="Section_Name", unique=false, nullable=true, insertable=true, updatable=true)
    public String getSectionName() {
        return this.sectionName;
    }

    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduSection")
    public Set<EduInstBranchSection> getEduInstBranchSections() {
        return this.eduInstBranchSections;
    }

    public void setEduInstBranchSections(Set<EduInstBranchSection> eduInstBranchSections) {
        this.eduInstBranchSections = eduInstBranchSections;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduSection")
    public Set<EduInstClassSection> getEduInstClassSections() {
        return this.eduInstClassSections;
    }

    public void setEduInstClassSections(Set<EduInstClassSection> eduInstClassSections) {
        this.eduInstClassSections = eduInstClassSections;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="eduSection")
    public Set<EduDocument> getEduDocuments() {
        return this.eduDocuments;
    }

    public void setEduDocuments(Set<EduDocument> eduDocuments) {
        this.eduDocuments = eduDocuments;
    }

}
