package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EduStudentMarks generated by hbm2java
 */
@Entity
@Table(name="edu_student_marks")
public class EduStudentMarks  extends BaseEntity {

    // Fields

     private EduStudentExam eduStudentExam;
     private EduSubject eduSubject;
     private int marks;
     private char isSms;
     private char isEmail;

     // Constructors

    /** default constructor */
    public EduStudentMarks() {
    }

    // Property accessors

@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Student_Exam_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduStudentExam getEduStudentExam() {
        return this.eduStudentExam;
    }

    public void setEduStudentExam(EduStudentExam eduStudentExam) {
        this.eduStudentExam = eduStudentExam;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Subject_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduSubject getEduSubject() {
        return this.eduSubject;
    }

    public void setEduSubject(EduSubject eduSubject) {
        this.eduSubject = eduSubject;
    }

    @Column(name="Marks", unique=false, nullable=false, insertable=true, updatable=true)
    public int getMarks() {
        return this.marks;
    }

    public void setMarks(int marks) {
        this.marks = marks;
    }

    @Column(name="Is_SMS", unique=false, nullable=false, insertable=true, updatable=true, length=1)
    public char getIsSms() {
        return this.isSms;
    }

    public void setIsSms(char isSms) {
        this.isSms = isSms;
    }

    @Column(name="Is_Email", unique=false, nullable=false, insertable=true, updatable=true, length=1)
    public char getIsEmail() {
        return this.isEmail;
    }

    public void setIsEmail(char isEmail) {
        this.isEmail = isEmail;
    }
}
