package com.edu.app.domain;
// Generated Jul 5, 2008 9:25:16 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EduUserStudent generated by hbm2java
 */
@Entity
@Table(name="edu_user_student")
public class EduUserStudent  extends BaseEntity {

    // Fields
     private EduUser eduUser;
     private EduStudent eduStudent;

     // Constructors

    /** default constructor */
    public EduUserStudent() {
    }

    // Property accessors

@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_User_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduUser getEduUser() {
        return this.eduUser;
    }

    public void setEduUser(EduUser eduUser) {
        this.eduUser = eduUser;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)

    @JoinColumn(name="Fk_Student_Id", unique=false, nullable=false, insertable=true, updatable=true)
    public EduStudent getEduStudent() {
        return this.eduStudent;
    }

    public void setEduStudent(EduStudent eduStudent) {
        this.eduStudent = eduStudent;
    }
}
